[theme]
base = "light"
primaryColor = "#6366F1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F9"
textColor = "#18181B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
